# Generated by Django 2.1.5 on 2019-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
