spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmpe451?allowPublicKeyRetrieval=true
    # use this if the above raises error:
    # jdbc:mysql://localhost:3306/cmpe451?useSSH=false

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: thread
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080 # Default application port
   url: http://localhost

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 1800000 # 30 minutes duration by default (in miliseconds)
  alpha-api-key1: "***************"
  alpha-api-key2: "***************"

email:
  sender_address: "bounswegroup6@gmail.com"
  sender_password: "*********"

  # Reset link is active on the backend side and waiting for a frontend page
  # to make user able to enter new pw and send that pw with token to
  # /renew endpoint on backend side.
  frontend_url: http://localhost # To which reset password link will redirect clients
  frontend_port: 3000 # TBD
  frontend_reset_path: renew_password # TBD, up to frontend team
  frontend_verification_path : register/confirm # decided on frontend side
