spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmpe451?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080 # Default application port

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 1800000 # 30 minutes duration by default (in miliseconds)
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

TrialController:
  admin: Auth test for admin role only
  trader: Auth test for trader and admin roles only
  basic: Auth test for all registered users
  public: Public test message